class WhisperTranscriptionService:
    def download_audio(self, video_id: str) -> str:
        """
        Stub for downloading audio from YouTube video.
        Returns path to audio file.
        """
        print(f"Stub: Downloading audio for video {video_id}...")
        return f"/tmp/{video_id}.mp3"

    def transcribe(self, video_id: str) -> str:
        """
        Stub for transcribing audio using Whisper.
        Returns transcript text.
        """
        audio_path = self.download_audio(video_id)
        print(f"Stub: Transcribing audio from {audio_path} using Whisper...")
        
        # Placeholder text
        return f"This is a placeholder transcript for video {video_id} generated by the Whisper service stub."
